// Array object of all the fish details available
// Scientific_name is not needed, as it is populated automatically for the ones listed here.
// Test using console.log at the bottom, after adding a fish.  If the scientific name isn't found in the online database, then you can add it here instead.
// For reference only, the scientific_names that are populated from the API have the populatedFromAPI placeholder name.
// That field is overwritten by the API.
// The api_id_name must match the actual naming convention in the API that is different in some cases.
const knownFishDetails = [
  {
    "api_id_name": "Largemouth black bass",
    "scientific_name": "populatedFromAPI",
    "common_name": "Largemouth bass", 
    "alt_names": ["Largemouth black bass"],
    "appearance": "Olive-green to greenish gray with the lower jaw extruding further than the upper.",
    "average_size": "18 inches",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": ["Almost anything from crayfish to large insects"],
    "hotspots": "Shaded areas during the day, deeper water under logs in the evening",
    "season": "Spring and Summer when the weather is warm. Inactive during winter.",
    "time_of_day": "Early morning or evening",
    "lifespan": "16 years",
    "image": "",
  },
  {
    "api_id_name": "Rock bass",
    "scientific_name": "populatedFromAPI",
    "common_name": "Rock bass", 
    "alt_names": [""],    
    "appearance": "Red eyes with six spines in the anal fin. Rows of black dots on its sides. A spined dorsal fin united with a soft-rayed one.",
    "average_size": "7 inches",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": ["Lake Superior", "Lake Michigan"],
    "popular_rivers": [""],
    "bait": ["Small fish", "Young rock bass", "Yellow perch", "Minnows", "Crawfish"],
    "hotspots": "Rocky lakes and rivers",
    "season": "Spring",
    "time_of_day": "Early morning or evening",
    "lifespan": "10 years",
    "image": "",
  },
  {
    "api_id_name": "Smallmouth bass",
    "scientific_name": "populatedFromAPI",
    "common_name": "Smallmouth bass", 
    "alt_names": [""],     
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "White bass",
    "scientific_name": "populatedFromAPI",
    "common_name": "White bass", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Bluegill",  
    "scientific_name": "populatedFromAPI",
    "common_name": "Bluegill", 
    "alt_names": [""],   
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Black bullhead",
    "scientific_name": "populatedFromAPI",
    "common_name": "Black bullhead", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Yellow bullhead",
    "scientific_name": "populatedFromAPI",
    "common_name": "Yellow bullhead", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Brown bullhead",
    "scientific_name": "populatedFromAPI",
    "common_name": "Brown bullhead", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Channel catfish",
    "scientific_name": "populatedFromAPI",
    "common_name": "Channel catfish", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Flathead catfish",
    "scientific_name": "populatedFromAPI",
    "common_name": "Flathead catfish", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Black crappie",
    "scientific_name": "populatedFromAPI",
    "common_name": "Black crappie", 
    "alt_names": [""], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Muskellunge",
    "scientific_name": "Esox masquinongy",
    "common_name": "Muskellunge", 
    "alt_names": ["Musky", "Muskie", "Lunge"], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "American yellow perch",
    "scientific_name": "populatedFromAPI",
    "common_name": "Yellow perch", 
    "alt_names": ["American yellow perch"], 
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Northern pike",
    "scientific_name": "populatedFromAPI",
    "common_name": "Northern pike", 
    "alt_names": [""],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Pumpkinseed",
    "scientific_name": "populatedFromAPI",
    "common_name": "Pumpkinseed", 
    "alt_names": [""],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Chinook(=Spring=King)salmon",
    "scientific_name": "populatedFromAPI",
    "common_name": "Chinook salmon", 
    "alt_names": ["Spring salmon", "King salmon"],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Coho(=Silver)salmon",
    "scientific_name": "populatedFromAPI",
    "common_name": "Coho salmon", 
    "alt_names": ["Silver salmon"],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Lake sturgeon",
    "scientific_name": "populatedFromAPI",
    "common_name": "Lake sturgeon", 
    "alt_names": [""],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Brook trout",
    "scientific_name": "populatedFromAPI",
    "common_name": "Brook trout", 
    "alt_names": [""],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Lake trout(=Char)", 
    "scientific_name": "populatedFromAPI",
    "common_name": "Lake trout",     
    "alt_names": ["Lake char"],    
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Brown trout",
    "scientific_name": "Salmo trutta",
    "common_name": "Brown trout", 
    "alt_names": [""],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Walleye",
    "scientific_name": "populatedFromAPI",
    "common_name": "Walleye", 
    "alt_names": [""],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "",
  },
  {
    "api_id_name": "Rainbow trout",
    "scientific_name": "populatedFromAPI",
    "common_name": "Rainbow trout", 
    "alt_names": ["Steelhead", "Steelhead trout"],
    "appearance": "",
    "average_size": "",
    "estimated_population": "",
    "states": ["Wisconsin"],
    "popular_lakes": [""],
    "popular_rivers": [""],
    "bait": [""],
    "hotspots": "",
    "season": "",
    "time_of_day": "",
    "lifespan": "",
    "image": "rainbow_trout_sm.jpg",
  },
];
// To display the list of these objects in the console for quick verification
// console.log(knownFishDetails);